# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: yunaichun blog
description: "Jekyll theme blog"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: https://yunaichun.github.io
baseurl: ""

google_analytics: UA-52446115-1
repo: https://github.com/yunaichun
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Naichun Yu
  job: Frontend Engineer
  bio: "Love programming, love frontend, love Challenges, always looking for the best project."
  thumb: /images/github.png
  url: https://yunaichun.github.io
  github: https://github.com/yunaichun
  email: naichunyu@aliyun.com
  phone: 13132290863

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
